"""Create work experience table

Revision ID: a37fd22e4f0c
Revises: a1df8d93ae91
Create Date: 2025-07-07 17:11:29.493272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37fd22e4f0c'
down_revision: Union[str, Sequence[str], None] = 'a1df8d93ae91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('professional_field_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('position_title', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_work_experience_city_id_cities')),
    sa.ForeignKeyConstraint(['professional_field_id'], ['professional_fields.id'], name=op.f('fk_work_experience_professional_field_id_professional_fields')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_work_experience_resume_id_resumes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_experience'))
    )
    op.create_index(op.f('ix_work_experience_id'), 'work_experience', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_experience_id'), table_name='work_experience')
    op.drop_table('work_experience')
    # ### end Alembic commands ###
