"""Create vacancies_work_location_types table

Revision ID: 42e36244b20a
Revises: e588769ae9cb
Create Date: 2025-07-08 11:07:49.315405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e36244b20a'
down_revision: Union[str, Sequence[str], None] = 'e588769ae9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies_work_location_types',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('work_location_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('fk_vacancies_work_location_types_vacancy_id_vacancies')),
    sa.ForeignKeyConstraint(['work_location_type_id'], ['work_location_types.id'], name=op.f('fk_vacancies_work_location_types_work_location_type_id_work_location_types')),
    sa.PrimaryKeyConstraint('vacancy_id', 'work_location_type_id', name=op.f('pk_vacancies_work_location_types'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies_work_location_types')
    # ### end Alembic commands ###
