"""Create professional fields table

Revision ID: 212e5dc429ed
Revises: 6212a70e8206
Create Date: 2025-07-07 14:48:57.069497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212e5dc429ed'
down_revision: Union[str, Sequence[str], None] = '6212a70e8206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professional_fields')),
    sa.UniqueConstraint('name', name=op.f('uq_professional_fields_name'))
    )
    op.create_index(op.f('ix_professional_fields_id'), 'professional_fields', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_fields_id'), table_name='professional_fields')
    op.drop_table('professional_fields')
    # ### end Alembic commands ###
