"""Add education_level_id column to vacancies table

Revision ID: 41dfa3fe17c2
Revises: 080f4e452347
Create Date: 2025-07-08 14:50:05.656503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41dfa3fe17c2'
down_revision: Union[str, Sequence[str], None] = '080f4e452347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('education_level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_vacancies_education_level_id_education_levels'), 'vacancies', 'education_levels', ['education_level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_vacancies_education_level_id_education_levels'), 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'education_level_id')
    # ### end Alembic commands ###
