"""Create vacancies employment types table

Revision ID: e588769ae9cb
Revises: 74f7caeb22e8
Create Date: 2025-07-08 10:52:45.230849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e588769ae9cb'
down_revision: Union[str, Sequence[str], None] = '74f7caeb22e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies_employment_types',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('employment_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employment_type_id'], ['employment_types.id'], name=op.f('fk_vacancies_employment_types_employment_type_id_employment_types')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('fk_vacancies_employment_types_vacancy_id_vacancies')),
    sa.PrimaryKeyConstraint('vacancy_id', 'employment_type_id', name=op.f('pk_vacancies_employment_types'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies_employment_types')
    # ### end Alembic commands ###
