"""Add city_id column to users

Revision ID: ef47df19d725
Revises: 10d17692252f
Create Date: 2025-07-07 12:52:21.087159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef47df19d725'
down_revision: Union[str, Sequence[str], None] = '10d17692252f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_city_id_cities'), 'users', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_city_id_cities'), 'users', type_='foreignkey')
    op.drop_column('users', 'city_id')
    # ### end Alembic commands ###
