"""Create resumes cities table

Revision ID: ecf029b0ba70
Revises: 7b8fd4ec69b6
Create Date: 2025-07-07 20:54:22.061996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf029b0ba70'
down_revision: Union[str, Sequence[str], None] = '7b8fd4ec69b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes_cities',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_resumes_cities_city_id_cities')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resumes_cities_resume_id_resumes')),
    sa.PrimaryKeyConstraint('resume_id', 'city_id', name=op.f('pk_resumes_cities'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes_cities')
    # ### end Alembic commands ###
