"""Create resumes employment types table

Revision ID: 1f8e10c844e5
Revises: b3a112f5d4fd
Create Date: 2025-07-07 19:31:11.746189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8e10c844e5'
down_revision: Union[str, Sequence[str], None] = 'b3a112f5d4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes_employment_types',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('employment_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employment_type_id'], ['employment_types.id'], name=op.f('fk_resumes_employment_types_employment_type_id_employment_types')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resumes_employment_types_resume_id_resumes')),
    sa.PrimaryKeyConstraint('resume_id', 'employment_type_id', name=op.f('pk_resumes_employment_types'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes_employment_types')
    # ### end Alembic commands ###
