"""Create responses table

Revision ID: 74f7caeb22e8
Revises: da3bdc8a2c4c
Create Date: 2025-07-08 10:37:55.964132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f7caeb22e8'
down_revision: Union[str, Sequence[str], None] = 'da3bdc8a2c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('response_status_id', sa.Integer(), nullable=False),
    sa.Column('cover_letter', sa.String(length=500), nullable=True),
    sa.Column('employer_response', sa.String(length=500), nullable=True),
    sa.Column('employer_response_date', sa.Date(), nullable=True),
    sa.Column('applicant_response_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['response_status_id'], ['response_statuses.id'], name=op.f('fk_responses_response_status_id_response_statuses')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_responses_resume_id_resumes')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('fk_responses_vacancy_id_vacancies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responses'))
    )
    op.create_index(op.f('ix_responses_id'), 'responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_id'), table_name='responses')
    op.drop_table('responses')
    # ### end Alembic commands ###
