"""Create vacancies cities table

Revision ID: 080f4e452347
Revises: 63d2cfadfb0f
Create Date: 2025-07-08 12:09:29.949046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080f4e452347'
down_revision: Union[str, Sequence[str], None] = '63d2cfadfb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies_cities',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_vacancies_cities_city_id_cities')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('fk_vacancies_cities_vacancy_id_vacancies')),
    sa.PrimaryKeyConstraint('vacancy_id', 'city_id', name=op.f('pk_vacancies_cities'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies_cities')
    # ### end Alembic commands ###
