"""Create resumes_work_location_types table

Revision ID: ffb12eff5d0d
Revises: c4cdfa153c03
Create Date: 2025-07-07 20:04:04.939120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb12eff5d0d'
down_revision: Union[str, Sequence[str], None] = 'c4cdfa153c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes_work_location_types',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('work_location_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resumes_work_location_types_resume_id_resumes')),
    sa.ForeignKeyConstraint(['work_location_type_id'], ['work_location_types.id'], name=op.f('fk_resumes_work_location_types_work_location_type_id_work_location_types')),
    sa.PrimaryKeyConstraint('resume_id', 'work_location_type_id', name=op.f('pk_resumes_work_location_types'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes_work_location_types')
    # ### end Alembic commands ###
