"""Create resumes professional fields table

Revision ID: 7b8fd4ec69b6
Revises: ffb12eff5d0d
Create Date: 2025-07-07 20:24:18.695092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8fd4ec69b6'
down_revision: Union[str, Sequence[str], None] = 'ffb12eff5d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes_professional_fields',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('professional_field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_field_id'], ['professional_fields.id'], name=op.f('fk_resumes_professional_fields_professional_field_id_professional_fields')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resumes_professional_fields_resume_id_resumes')),
    sa.PrimaryKeyConstraint('resume_id', 'professional_field_id', name=op.f('pk_resumes_professional_fields'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes_professional_fields')
    # ### end Alembic commands ###
