"""Create response statuses table

Revision ID: da3bdc8a2c4c
Revises: bd22798d2760
Create Date: 2025-07-08 09:27:57.211952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3bdc8a2c4c'
down_revision: Union[str, Sequence[str], None] = 'bd22798d2760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_response_statuses')),
    sa.UniqueConstraint('name', name=op.f('uq_response_statuses_name'))
    )
    op.create_index(op.f('ix_response_statuses_id'), 'response_statuses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_statuses_id'), table_name='response_statuses')
    op.drop_table('response_statuses')
    # ### end Alembic commands ###
