"""Create user_roles_permissions table

Revision ID: 7d5aebb8c38d
Revises: ac0f09a4bf1d
Create Date: 2025-07-17 22:08:23.547714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5aebb8c38d'
down_revision: Union[str, Sequence[str], None] = 'ac0f09a4bf1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles_permissions',
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_user_roles_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], name=op.f('fk_user_roles_permissions_user_role_id_user_roles')),
    sa.PrimaryKeyConstraint('user_role_id', 'permission_id', name=op.f('pk_user_roles_permissions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles_permissions')
    # ### end Alembic commands ###
