"""Create education tables

Revision ID: b3a112f5d4fd
Revises: a37fd22e4f0c
Create Date: 2025-07-07 17:42:07.783394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a112f5d4fd'
down_revision: Union[str, Sequence[str], None] = 'a37fd22e4f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education_levels')),
    sa.UniqueConstraint('name', name=op.f('uq_education_levels_name'))
    )
    op.create_index(op.f('ix_education_levels_id'), 'education_levels', ['id'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education_level_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=False),
    sa.Column('graduation_year', sa.Date(), nullable=False),
    sa.Column('specialty_name', sa.String(length=140), nullable=False),
    sa.ForeignKeyConstraint(['education_level_id'], ['education_levels.id'], name=op.f('fk_education_education_level_id_education_levels')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_education_resume_id_resumes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education'))
    )
    op.create_index(op.f('ix_education_id'), 'education', ['id'], unique=False)

    op.bulk_insert(
        sa.table(
            'education_levels',
            sa.column('name', sa.String),
        ),
        [
            {'name': 'Середня'},
            {'name': 'Середня спеціальна'},
            {'name': 'Незакінчена вища'},
            {'name': 'Вища'},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_education_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_education_levels_id'), table_name='education_levels')
    op.drop_table('education_levels')
    # ### end Alembic commands ###
