"""Create education tables

Revision ID: 83b4baa9b23e
Revises: ef47df19d725
Create Date: 2025-07-07 13:14:56.574145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b4baa9b23e'
down_revision: Union[str, Sequence[str], None] = 'ef47df19d725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education_levels')),
    sa.UniqueConstraint('name', name=op.f('uq_education_levels_name'))
    )
    op.create_index(op.f('ix_education_levels_id'), 'education_levels', ['id'], unique=False)
    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education_level_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=False),
    sa.Column('graduation_year', sa.Date(), nullable=False),
    sa.Column('specialty_name', sa.String(length=140), nullable=False),
    sa.ForeignKeyConstraint(['education_level_id'], ['education_levels.id'], name=op.f('fk_educations_education_level_id_education_levels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_educations'))
    )
    op.create_index(op.f('ix_educations_id'), 'educations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_educations_id'), table_name='educations')
    op.drop_table('educations')
    op.drop_index(op.f('ix_education_levels_id'), table_name='education_levels')
    op.drop_table('education_levels')
    # ### end Alembic commands ###
