"""Create vacancies professional fields table

Revision ID: 63d2cfadfb0f
Revises: 42e36244b20a
Create Date: 2025-07-08 11:56:12.212910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d2cfadfb0f'
down_revision: Union[str, Sequence[str], None] = '42e36244b20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies_professional_fields',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('professional_field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_field_id'], ['professional_fields.id'], name=op.f('fk_vacancies_professional_fields_professional_field_id_professional_fields')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('fk_vacancies_professional_fields_vacancy_id_vacancies')),
    sa.PrimaryKeyConstraint('vacancy_id', 'professional_field_id', name=op.f('pk_vacancies_professional_fields'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies_professional_fields')
    # ### end Alembic commands ###
