"""Create work location types table

Revision ID: c4cdfa153c03
Revises: 1f8e10c844e5
Create Date: 2025-07-07 19:50:18.183666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4cdfa153c03'
down_revision: Union[str, Sequence[str], None] = '1f8e10c844e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_location_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_location_types')),
    sa.UniqueConstraint('name', name=op.f('uq_work_location_types_name'))
    )
    op.create_index(op.f('ix_work_location_types_id'), 'work_location_types', ['id'], unique=False)

    op.bulk_insert(
        sa.table(
            'work_location_types',
            sa.column('name', sa.String),
        ),
        [
            {'name': 'Віддалена робота'},
            {'name': 'Гібридна робота'},
            {'name': 'Офіс/на місці'},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_location_types_id'), table_name='work_location_types')
    op.drop_table('work_location_types')
    # ### end Alembic commands ###
