"""Create employers table

Revision ID: 2b6226f0465a
Revises: 915ebcb8c872
Create Date: 2025-07-07 22:22:20.204314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6226f0465a'
down_revision: Union[str, Sequence[str], None] = '915ebcb8c872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employers'))
    )
    op.create_index(op.f('ix_employers_id'), 'employers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employers_id'), table_name='employers')
    op.drop_table('employers')
    # ### end Alembic commands ###
